{% set version = "9.2.1.5" %}
{% set onload_commit = "37e005884a9b9abfdc949386f550ada922bbff8e" %}

package:
  name: tcpdirect
  version: {{ version }}

source:
  - url: https://github.com/Xilinx-CNS/tcpdirect/archive/refs/tags/tcpdirect-{{ version }}.tar.gz
    sha256: a929265d4f0873a3ed4773b5780a2b07992b410e398d30dad3e62603ad60ec21
    folder: tcpdirect
    patches:
      - install.diff

  - url: https://github.com/Xilinx-CNS/onload/archive/{{ onload_commit }}.tar.gz
    sha256: 86eae21f1d870ebccfc71f1953301a314350afb34b91936f227da99f4b5f9170
    folder: onload

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
  host:
  run:

test:
  commands:
    - test -f $PREFIX/include/zf/zf_tcp.h
    - test -f $PREFIX/bin/zf_stackdump

about:
  home: https://www.xilinx.com/support/download/nic-software-and-drivers.html#tcpdirect
  summary: 'AMD TCPDirect ultra low latency kernel bypass TCP and UDP implementation for AMD Solarflare network adapters, to be used with corresponding versions of Onload'
  license: MIT AND BSD-3-Clause AND LGPL-3.0-only
  license_file: tcpdirect/doc/LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
