{% set version = "9.2.0.9" %}
{% set onload_commit = "6958af1c840490d0fb21ba8aa0d55368fe083cc4" %}

package:
  name: tcpdirect
  version: {{ version }}

source:
  - url: https://github.com/Xilinx-CNS/tcpdirect/archive/refs/tags/tcpdirect-{{ version }}.tar.gz
    sha256: 3fee39cdeb610a4ead126ff73c192def59586ed7fcc69f029bede6ae86babaae
    folder: tcpdirect
    patches:
      - install.diff

  - url: https://github.com/Xilinx-CNS/onload/archive/{{ onload_commit }}.tar.gz
    sha256: 14fb3aca15033a60c2da03b5040bcfc08c5a905af96739720d95ba56b811c257
    folder: onload

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
  host:
  run:

test:
  commands:
    - test -f $PREFIX/include/zf/zf_tcp.h
    - test -f $PREFIX/bin/zf_stackdump

about:
  home: https://www.xilinx.com/support/download/nic-software-and-drivers.html#tcpdirect
  summary: 'AMD TCPDirect ultra low latency kernel bypass TCP and UDP implementation for AMD Solarflare network adapters, to be used with corresponding versions of Onload'
  license: MIT AND BSD-3-Clause AND LGPL-3.0-only
  license_file: tcpdirect/doc/LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
